name: Load Test

on:
    push:
      branches:
        - main
        - master
    pull_request:
      branches:
        - main
        - master
    workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Artillery.io
        run: npm install -g artillery

      - name: Run Load Test
        run: |
          artillery run artillery/artillery.yml
